
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TuPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init.sql:/init.sql
    restart: always
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 70 && 
      echo 'Waiting for SQL Server to be ready...'; 
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'TuPassword123!' -C -d master -i /init.sql;
      wait
      "
    networks:
      - mynetwork

  webapp:
    build: .
    container_name: aspnet_app
    restart: always
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=billing_system;User Id=sa;Password=TuPassword123!;TrustServerCertificate=True;Connect Timeout=50"
    networks:
      - mynetwork

volumes:
  sql_data:

networks:
  mynetwork:
    driver: bridge
